name: Cron Scrap Scholarship Scraper

on:
  schedule:
    - cron: "0 2 * * *" # 2am UTC
  workflow_dispatch:

jobs:
  ping_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Call deployed scraper API
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -H "Authorization: Bearer $CRON_SECRET" -X GET https://grantly-ai.vercel.app/api/scraper
